classDiagram
    class BaseTest {
        -WebDriver browser
        -BankTransferSteps bankTransferSteps
        -LoginSteps loginSteps
        -LogoutSteps logoutSteps
        -NavigateActions navigateActions
        -SearchActions searchActions
        -SearchResultSidebar searchResultSidebar
        -SearchTextSteps searchTextSteps
    }
    class FundTransferTest {
        <<extends BaseTest>>
        +void fundTransfer_IntraBank()
        +void failure_fundTransfer_InterBank()
    }
    class WhenSearchingByKeywordTest {
        <<extends BaseTest>>
        +void theKeywordShouldAppearInTheResultsSidebar()
    }

    BaseTest <|-- FundTransferTest
    BaseTest <|-- WhenSearchingByKeywordTest
