classDiagram
    class BaseTest {
        -WebDriver browser
        -BankTransferSteps bankTransferSteps
        -LoginSteps loginSteps
        -LogoutSteps logoutSteps
    }
    class FundTransferTest {
        +fundTransfer_IntraBank()
        +failure_fundTransfer_InterBank()
    }

    FundTransferTest --|> BaseTest : extends
